config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  private
  
    def picture_size
        if picture.size > 5.megabytes
            errors.add(:picture, "should be less than 5MB")
        end
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
    belongs_to :user
    
    def self.month_options
        Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
    end
    
    def self.year_options
        (Date.today.year..(Date.today.year+10)).to_a
    end
    
    def process_payment
        customer = Stripe::Customer.create email: email, card: token
    
        Stripe::Charge.create customer: customer.id, 
                          amount: 1000, 
                          description: 'Premium', 
                          currency: 'usd'
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_one :payment
  accepts_nested_attributes_for :payment
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :picture).merge(user: current_user)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)
    
    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({ email: params["user"]["email"], 
          token: params[:payment]["token"], user_id: resource.id })
        
        flash[:error] = "Please check registration errors" unless @payment.valid?
        
        begin
          puts @payment.process_payment
          @payment.save
        rescue Exception => e 
          flash[:error] = e.message
          
          resource.destroy
          puts 'Payment failed'
          render :new and return
        end
        
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:payment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index]
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, :html => {multipart: true, :class => "form-horizontal image"}) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="card">
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= form.label :picture, class: "form-label" %>
        <%= form.file_field :picture, accept: 'image/jpeg,image/png,image/gif', class: "form-control" %>
      </div>
    
      <div class="actions">
        <%= form.submit class: "btn btn-outline-pink" %>
      </div>
    </div>
  </div>

  
<% end %>

<script type="text/javascript">
  $('#image_picture').bind('change', function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB')
    }
  })
</script>

app/views/images/edit.html.erb
<h2>
    Editing Image
    <div class="btn-group pull-right" role="group" aria-label="Basic example">
        <%= link_to 'Show', @image, class: "btn btn-info" %>
        <%= link_to 'Back', images_path, class: "btn btn-secondary" %>
    </div>
</h2>

<%= render 'form', image: @image %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>


<div class="card">
  <div class="card-header">
    <h2>
      Images
      <%= link_to 'New Image', new_image_path, class: "btn btn-outline-pink pull-right" %>
    </h2> 
  </div>
  <div class="card-body">
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Picture</th>
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @images.each do |image| %>
          <tr>
            <td><%= link_to image.name, image_path(image) %></td>
            <td><%= image_tag image.picture.url, size: "100x100" %></td>
            <td>
              <div class="btn-group pull-right" role="group" aria-label="Basic example">
                <%= link_to 'Show', image, class: "btn btn-outline-info" %>
                <%= link_to 'Edit', edit_image_path(image), class: "btn btn-outline-warning" %>
                <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/images/new.html.erb
<h2>
    New Image
    <%= link_to 'Back', images_path, class: "btn btn-secondary pull-right" %>
</h2>

<%= render 'form', image: @image %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center text-center">
<div class="card position-absolute" style="width: 50rem;">
  <%= image_tag(@image.picture.url, class: "card-img-top") if @image.picture? %>
  <div class="card-body">
    <h5 class="card-title"><%= @image.name %></h5>
    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <%= link_to 'Edit', edit_image_path(@image), class: "btn btn-outline-pink" %> |
    <%= link_to 'Back', images_path, class: "btn btn-secondary" %>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom py-4 footer">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Deen", "https://www.linkedin.com/in/dina-fajardo/", class: "text-pink" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
    <div class="alert alert-success %> alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

<% if alert %>
    <div class="alert alert-danger %> alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-pink">
  <div class="container-fluid">
    <%= link_to "PhotoApp", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Images", images_path, class: "nav-link" %>
        </li>
      </ul>
      
      
      <% if current_user %>
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %> 
          </li>
        </ul>
        <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      <% end %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container pt-5">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  <div class="jumbotron">
    <h3 class="welcome">Welcome, <%= current_user.email %>!</h3>
  </div>
<% else %>
  <div class="jumbotron">
    <h2>Welcome to the Photo Management App!</h2>
    <p class="lead">
      You'll love managing your Photos with our application. Sign up!
    </p>
  </div>
  
  <div class="container row mt-4">
    <div class="col-1"></div>
    <div class="col-4">
        <h2>Premium Plan</h2>
        <div class="price pull-right">
          Price: $10
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-pink sign-up' %>
        </p>
    </div>
    
    <div class="col-2"></div>
    <div class="col-4">
      <h2>Amaze Plan</h2>
        <div class="price pull-right">
          Price: $20
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
            <li class='extra'>Unlimited projects</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-pink sign-up' %>
        </p>
    </div>
    <div class="col-1"></div>
  </div>

<% end %>